spring.application.name=product-service

server.port=${PORT:8082}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:onedaywear_product}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}

# Image Upload Folder & Base URL
file.upload-dir=${FILE_UPLOAD_DIR:./uploads}
image.storage.type=${IMAGE_STORAGE_TYPE:local}
aws.access.key.id=${AWS_ACCESS_KEY_ID:}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY:}
aws.endpoint.url=${AWS_ENDPOINT_URL:}
aws.region=${AWS_REGION:}
aws.bucket.name=${BUCKET_NAME:}